// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetRowCountDemo.proto

package com.okingniko.coprocessor.demo;

public final class GetRowCount {
  private GetRowCount() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetRowCountRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool reCount = 1;
    /**
     * <code>required bool reCount = 1;</code>
     */
    boolean hasReCount();
    /**
     * <code>required bool reCount = 1;</code>
     */
    boolean getReCount();
  }
  /**
   * Protobuf type {@code GetRowCountRequest}
   */
  public static final class GetRowCountRequest extends
      com.google.protobuf.GeneratedMessage
      implements GetRowCountRequestOrBuilder {
    // Use GetRowCountRequest.newBuilder() to construct.
    private GetRowCountRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetRowCountRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetRowCountRequest defaultInstance;
    public static GetRowCountRequest getDefaultInstance() {
      return defaultInstance;
    }

    public GetRowCountRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetRowCountRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              reCount_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.okingniko.coprocessor.demo.GetRowCount.internal_static_GetRowCountRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.okingniko.coprocessor.demo.GetRowCount.internal_static_GetRowCountRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest.class, com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<GetRowCountRequest> PARSER =
        new com.google.protobuf.AbstractParser<GetRowCountRequest>() {
      public GetRowCountRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetRowCountRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetRowCountRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool reCount = 1;
    public static final int RECOUNT_FIELD_NUMBER = 1;
    private boolean reCount_;
    /**
     * <code>required bool reCount = 1;</code>
     */
    public boolean hasReCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool reCount = 1;</code>
     */
    public boolean getReCount() {
      return reCount_;
    }

    private void initFields() {
      reCount_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, reCount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, reCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetRowCountRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.okingniko.coprocessor.demo.GetRowCount.internal_static_GetRowCountRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.okingniko.coprocessor.demo.GetRowCount.internal_static_GetRowCountRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest.class, com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest.Builder.class);
      }

      // Construct using com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reCount_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.okingniko.coprocessor.demo.GetRowCount.internal_static_GetRowCountRequest_descriptor;
      }

      public com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest getDefaultInstanceForType() {
        return com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest.getDefaultInstance();
      }

      public com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest build() {
        com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest buildPartial() {
        com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest result = new com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reCount_ = reCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest) {
          return mergeFrom((com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest other) {
        if (other == com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest.getDefaultInstance()) return this;
        if (other.hasReCount()) {
          setReCount(other.getReCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReCount()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool reCount = 1;
      private boolean reCount_ ;
      /**
       * <code>required bool reCount = 1;</code>
       */
      public boolean hasReCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool reCount = 1;</code>
       */
      public boolean getReCount() {
        return reCount_;
      }
      /**
       * <code>required bool reCount = 1;</code>
       */
      public Builder setReCount(boolean value) {
        bitField0_ |= 0x00000001;
        reCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool reCount = 1;</code>
       */
      public Builder clearReCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reCount_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetRowCountRequest)
    }

    static {
      defaultInstance = new GetRowCountRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GetRowCountRequest)
  }

  public interface GetRowCountResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 rowCount = 1;
    /**
     * <code>optional int64 rowCount = 1;</code>
     */
    boolean hasRowCount();
    /**
     * <code>optional int64 rowCount = 1;</code>
     */
    long getRowCount();
  }
  /**
   * Protobuf type {@code GetRowCountResponse}
   */
  public static final class GetRowCountResponse extends
      com.google.protobuf.GeneratedMessage
      implements GetRowCountResponseOrBuilder {
    // Use GetRowCountResponse.newBuilder() to construct.
    private GetRowCountResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetRowCountResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetRowCountResponse defaultInstance;
    public static GetRowCountResponse getDefaultInstance() {
      return defaultInstance;
    }

    public GetRowCountResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetRowCountResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rowCount_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.okingniko.coprocessor.demo.GetRowCount.internal_static_GetRowCountResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.okingniko.coprocessor.demo.GetRowCount.internal_static_GetRowCountResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse.class, com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<GetRowCountResponse> PARSER =
        new com.google.protobuf.AbstractParser<GetRowCountResponse>() {
      public GetRowCountResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetRowCountResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetRowCountResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 rowCount = 1;
    public static final int ROWCOUNT_FIELD_NUMBER = 1;
    private long rowCount_;
    /**
     * <code>optional int64 rowCount = 1;</code>
     */
    public boolean hasRowCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 rowCount = 1;</code>
     */
    public long getRowCount() {
      return rowCount_;
    }

    private void initFields() {
      rowCount_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, rowCount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rowCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetRowCountResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.okingniko.coprocessor.demo.GetRowCount.internal_static_GetRowCountResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.okingniko.coprocessor.demo.GetRowCount.internal_static_GetRowCountResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse.class, com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse.Builder.class);
      }

      // Construct using com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rowCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.okingniko.coprocessor.demo.GetRowCount.internal_static_GetRowCountResponse_descriptor;
      }

      public com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse getDefaultInstanceForType() {
        return com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse.getDefaultInstance();
      }

      public com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse build() {
        com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse buildPartial() {
        com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse result = new com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rowCount_ = rowCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse) {
          return mergeFrom((com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse other) {
        if (other == com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse.getDefaultInstance()) return this;
        if (other.hasRowCount()) {
          setRowCount(other.getRowCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 rowCount = 1;
      private long rowCount_ ;
      /**
       * <code>optional int64 rowCount = 1;</code>
       */
      public boolean hasRowCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 rowCount = 1;</code>
       */
      public long getRowCount() {
        return rowCount_;
      }
      /**
       * <code>optional int64 rowCount = 1;</code>
       */
      public Builder setRowCount(long value) {
        bitField0_ |= 0x00000001;
        rowCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 rowCount = 1;</code>
       */
      public Builder clearRowCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rowCount_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetRowCountResponse)
    }

    static {
      defaultInstance = new GetRowCountResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GetRowCountResponse)
  }

  /**
   * Protobuf service {@code GetRowCountService}
   */
  public static abstract class GetRowCountService
      implements com.google.protobuf.Service {
    protected GetRowCountService() {}

    public interface Interface {
      /**
       * <code>rpc getRowCount(.GetRowCountRequest) returns (.GetRowCountResponse);</code>
       */
      public abstract void getRowCount(
          com.google.protobuf.RpcController controller,
          com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest request,
          com.google.protobuf.RpcCallback<com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new GetRowCountService() {
        @java.lang.Override
        public  void getRowCount(
            com.google.protobuf.RpcController controller,
            com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest request,
            com.google.protobuf.RpcCallback<com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse> done) {
          impl.getRowCount(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getRowCount(controller, (com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getRowCount(.GetRowCountRequest) returns (.GetRowCountResponse);</code>
     */
    public abstract void getRowCount(
        com.google.protobuf.RpcController controller,
        com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest request,
        com.google.protobuf.RpcCallback<com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.okingniko.coprocessor.demo.GetRowCount.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getRowCount(controller, (com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest)request,
            com.google.protobuf.RpcUtil.<com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.okingniko.coprocessor.demo.GetRowCount.GetRowCountService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getRowCount(
          com.google.protobuf.RpcController controller,
          com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest request,
          com.google.protobuf.RpcCallback<com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse.class,
            com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse getRowCount(
          com.google.protobuf.RpcController controller,
          com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse getRowCount(
          com.google.protobuf.RpcController controller,
          com.okingniko.coprocessor.demo.GetRowCount.GetRowCountRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.okingniko.coprocessor.demo.GetRowCount.GetRowCountResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:GetRowCountService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRowCountRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetRowCountRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRowCountResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetRowCountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025GetRowCountDemo.proto\"%\n\022GetRowCountRe" +
      "quest\022\017\n\007reCount\030\001 \002(\010\"\'\n\023GetRowCountRes" +
      "ponse\022\020\n\010rowCount\030\001 \001(\0032N\n\022GetRowCountSe" +
      "rvice\0228\n\013getRowCount\022\023.GetRowCountReques" +
      "t\032\024.GetRowCountResponseB2\n\036com.okingniko" +
      ".coprocessor.demoB\013GetRowCountH\001\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GetRowCountRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GetRowCountRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GetRowCountRequest_descriptor,
              new java.lang.String[] { "ReCount", });
          internal_static_GetRowCountResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_GetRowCountResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GetRowCountResponse_descriptor,
              new java.lang.String[] { "RowCount", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
